on: 
  push:
    tags:
      - 'v*'

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export Game
    steps:
    - name: checkout
      uses: actions/checkout@v3.2.0
      with:
        fetch-depth: 0

    - name: export game
      id: export
      uses: firebelley/godot-export@v4.4.0
      with:
        godot_executable_download_url: https://github.com/godotengine/godot/releases/download/3.5.3-stable/Godot_v3.5.3-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/3.5.3-stable/Godot_v3.5.3-stable_export_templates.tpz
        relative_project_path: ./
        wine_path: ${{ steps.wine_install.outputs.WINE_PATH }}
        # if the PCK is seperate use archive_output: true

    - name: create release
      uses: ncipollo/release-action@v1.12.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
        tag: ${{ github.ref_name }}
        artifacts: ${{ steps.export.outputs.build_directory }}/*
        # if the archive_output is set u can use artifacts: ${{ steps.export.outputs.archive_directory }}/*
